gscam_publisher:
  ros__parameters:
    gscam_config: "v4l2src device=/dev/video2 do-timestamp=true ! video/x-raw,width=640,height=480,framerate=30/1 ! timeoverlay ! videoconvert"
    sync_sink: True
    preroll: True
    use_gst_timestamp: True
    # Camera_info_url, produces error when specified here. 
    # camera_info_url: "file://$PWD/src/gscam2/config/ost.ini"
    camera_name: "my_camera"
    frame_id: 'my_camera_frame'